<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AzureFunctionsVersion>V4</AzureFunctionsVersion>
        <OutputType>Exe</OutputType>
      <UserSecretsId>1f35ef88-83c1-48b0-9691-6be191f04e79</UserSecretsId>
      <RootNamespace>FfAdmin.EventImport.Function</RootNamespace>
      <WarningsNotAsErrors>$(WarningsNotAsErrors);NU1510</WarningsNotAsErrors>
      
  </PropertyGroup>
    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
      <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.51.0" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.3.0" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.24.0" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.1.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.12" IncludeAssets="development" ExcludeAssets="all"/>
        
    </ItemGroup>
    <ItemGroup>
        <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="local.settings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Calculator.ApiClient\Calculator.ApiClient.csproj" />
      <ProjectReference Include="..\EventStore.ApiClient\EventStore.ApiClient.csproj" />
      <ProjectReference Include="..\ExchangeRate\ExchangeRate.csproj" />
      <ProjectReference Include="..\External.GiveWp.ApiClient\External.GiveWp.ApiClient.csproj" />
      <ProjectReference Include="..\External.Mollie.ApiClient\External.Mollie.ApiClient.csproj" />
      <ProjectReference Include="..\External.Stripe.ApiClient\External.Stripe.ApiClient.csproj" />
    </ItemGroup>
</Project>